# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8b3863c985f4e56cda1353309343ce289764b36eadd0293f0c581a8331668af9687c048de764cc7f462900b8f42d791684273b8c02d20f123d97cec2a50a6c5

test:
  secret_key_base: 0a95f1bb58a5a013f41dcbe28cd9725ec8ecf8b7b9c410665cf54c294c8a9799e9c5d0b89d16b98c553c1cf6238b712e53c66f140323ba172bc412614e95c031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
